version: "3.1"
services:
    client:
        container_name: isobar_client
        build:
            context: ./client
            dockerfile: Dockerfile
        image: isobar_client
        ports:
            - 80:80
        depends_on:
            - server
    server:
        container_name: isobar_server
        build:
            context: ./server
            dockerfile: Dockerfile
        environment:
            PORT: 4000
        image: isobar_server
        ports:
            - 4000:4000
        depends_on:
            - redis
    redis:
        container_name: isobar_redis
        image: redis
        command: redis-server
